### PR TITLE
Undo changes from #40 (anomaly log plot) as these were not the appropriate fix.

### PR DESCRIPTION
**Pull request by trexfeathers**
Undo changes from #40 (anomaly log plot) as these were not the appropriate fix. The appropriate fix has been achieved via SciTools/iris#4115.

### CODE REVIEW

**Review by rcomer — APPROVED** [review]
LGTM

**Comment by pp-mo** [comment]
Could we have avoided *removing* this ?
Ideally, we should never **remove** things from this repo, 
because it's not just iris::main that may be relying on it...

Removing this file has messed up the test in [this PR](https://github.com/SciTools/iris/pull/4224)
Because the PR is based against a different branch (mesh-data-model), the PR can't merge the change to `imagerepo.json` that removes the reference to this file -- because that is only in the main branch.
But, if I make that change on the PR branch, it will (eventually) cause a merge conflict when we try to merge the mesh-data-model branch back...

**Comment by trexfeathers** [comment]
>Could we have avoided *removing* this ?

I hear what you're saying, but so long as the image was in this repo it was possible for tests to pass despite invalid behaviour. Preserving invalid software behaviour to ease source control seems like a big anti-pattern to me. Would there have been a third way that I haven't thought of?

**Comment by pp-mo** [comment]
> >  Could we have avoided removing this ?
> I hear what you're saying, but so long as the image was in this repo it was possible for tests to pass despite invalid behaviour. 

I still think this was wrong, really.
I found it causing [more trouble](https://github.com/SciTools/iris/pull/4224#issuecomment-874852323)
> @pp-mo you also need to bring in the correct use of linscale from #4115.

But..
> ... Would there have been a third way that I haven't thought of?

Unfortunately no, I don't think there is.

---

The real problem here, possibly, is that we don't version our use of test-iris-imagehash at all -- we don't specify a commits, tag, or version of the repo.
So, **_all_** testing occurs against the current latest content.  
So in that case, the big problem with any non-additive change is that it may break testing of _older_ versions of Iris.
**_I_** think it should really be possible to go back to any older version  of Iris (a release, or a trunk commit) and still have it pass all the tests (for comparison, obviously).

In this case, that included the problem PR, because being based on a feature-branch, subsequent changes to 'main' are not merged to it.  So, it can only run against the latest test-iris-imagehash if it also contains the required changes to the test.

So, in hopes of coming up with some guiding principles.
All totally ***In my view ...***
  * the result that was removed was "a valid answer to the wrong question".  
  * but changing the question **_doesn't_** mean we should remove results that were "previously judged correct"

Of course, the mechanism _does_ leave the door open to a future error producing the same image result,  which would then be definitely a wrong answer, yet (erroneously) pass the test. 
But I think we just have to trust that the "space of wrong results" is large enough that, statistically, cases like that will be very rare.
Whereas, deciding that what used to be "correct" no longer is, does risk breaking the workflow.
I _think_ a viable alternative would be to version/tag the state of test-iris-imagehash, as we do with iris-test-data.

**Pull request merged**
