### PR TITLE
Added new image for anomaly plot in matplotlib > 3.4

### PR DESCRIPTION
**Pull request by jamesp**
This adds a new version of the anomaly plot, added to `imagerepo.json` in [SciTools/iris#4108](https://github.com/SciTools/iris/pull/4108).

I hope I have done this correctly, please let me know if not

### CODE REVIEW

**Comment by rcomer** [comment]
I think that `linscale` should have been set to 0.1 rather than 1.  This way the scale looks more sensible to me, and closer to what is in our [stable docs](https://scitools-iris.readthedocs.io/en/stable/generated/gallery/general/plot_anomaly_log_colouring.html#sphx-glr-generated-gallery-general-plot-anomaly-log-colouring-py).

anomalylog

This setting doesn't get the test passing though, so we would need new hashes regardless!

**Comment by trexfeathers** [comment]
To confirm my understanding:

We had another recent change to this image test in #40. This claimed to be for Matplotlib `v3.4.1`, but the CI has _actually_ been [running against Matplotlib `v3.3.4` until more recently](https://cirrus-ci.com/task/6531977575661568?logs=tests#L132). Now that CI is [running against `v3.4.1`](https://cirrus-ci.com/task/4674708315570176?logs=tests#L166), a further minor behaviour change can be seen, necessitating a further change to the test target.

On a different thread: I would prefer to see @rcomer's suggestion a reality, as this would indeed get things back to how they were before #40. I see now that I should not have merged #40; with no prior knowledge, I had assumed @bjlittle's change there was the closest we could get in the new world, but clearly I was wrong.

**Comment by rcomer** [comment]
In fact, if I set `linscale` to 0.01, the gallery test passed :+1: .  Got a bit confused about exactly what `linscale` does.  I think the key thing is that the value is arbitrarily small.

**Comment by jamesp** [comment]
Closing this issue as it's not the right fix!  Let's open a separate PR on iris with @rcomer's suggested change above

**Pull request closed without merging**
