### PR TITLE
Images for iris.tests.integration.plot.test_vector_plots.

### PR DESCRIPTION
**Pull request by pp-mo**
Test plots for https://github.com/SciTools/iris/pull/3158

### CODE REVIEW

**Comment by ajdawson** [comment]
The case for streamplot latlon_2d_polar looks wrong, the streamlines extend outside the map boundary.

**Comment by pp-mo** [comment]
> @ajdawson the streamlines extend outside the map boundary.

I don't see why that is necessarily wrong ?

If you compare the 'non-latlon 2d' outputs ...
 [quiver](https://github.com/SciTools/test-iris-imagehash/blob/79a86034a5e7b0eb8ea17595c4a6ef3a2d309456/images/v4/afac24b6785171c93497632ce47c64b66526c4f392593b4d37266d26ccf232d2.png) 
and  [streamplot](https://github.com/SciTools/test-iris-imagehash/blob/79a86034a5e7b0eb8ea17595c4a6ef3a2d309456/images/v4/e97870638785658c64043971687b6767e46e3c6491b369bec62c3a79785a6763.png) 
... you see that the coordinate range of the quiver plot (i.e. the coords used) is x=[0, 5] and y=[0, 4],
but the bounding rectangle of the corresponding streamplot is x=[0, 6] and y=[0, 5].
It basically just does that.

Pragmatically, I'm not at all sure how this could be fixed, anyway.  Presumably it would need special support in cartopy, because I don't think the matplotlib command provides sufficient flexibility to allow you to control this aspect ?

**Comment by pp-mo** [comment]
Ok, on closer inspection I found that all this is completely wrong-headed because streamplot does not do what I thought ...
See : https://github.com/SciTools/iris/pull/3158#issuecomment-418372558

**Comment by pp-mo** [comment]
I've now ditched streamplot entirely.
Does this look ok now @ajdawson and/or @lbdreyer ?

**Comment by lbdreyer** [comment]
I'm happy with this. Just a shame about the streamplot

**Pull request merged**
