### PR TITLE
New images for mpl3x2 changes

### PR DESCRIPTION
**Pull request by pp-mo**
More fallout from matplotlib v3.2
Onwards from #29 -- more was needed to fix.

### CODE REVIEW

**Review by trexfeathers — CHANGES_REQUESTED** [review]
These changes match the original 12 failures that [Iris PR 3682](https://github.com/SciTools/iris/pull/3682) addresses, however the latest commit for 3682 has [highlighted some new failures that need investigating](https://github.com/SciTools/iris/pull/3682#pullrequestreview-376818844). Assuming the investigation yields more new image hashes we should get them all into this PR so this should not be merged yet.

**Comment by pp-mo** [comment]
Hi @trexfeathers thanks for your patience.
I think all those extra failures are ones that only emerge on a re-run when you have fixed the first set of errors.  Which I forgot to do ..
Ironically, just one of the things I have just been [painstakingly re-documenting](https://github.com/SciTools/iris/pull/3683).

**Comment by trexfeathers** [comment]
> Ironically, just one of the things I have just been painstakingly re-documenting.

Hadn't escaped my notice 😂

**Review by trexfeathers — APPROVED** [review]
Can confirm the latest 7 additions address the [additional 7 failures highlighted here](https://github.com/SciTools/iris/pull/3682#pullrequestreview-376818844). All good, thanks @pp-mo 👍

**Pull request merged**
