### PR TITLE
Fill between

### PR DESCRIPTION
**Pull request by wjbenfold**
Images for https://github.com/SciTools/iris/pull/4647

### CODE REVIEW

**Comment by trexfeathers** [comment]
I think with was superceded by SciTools/iris-test-data#78

**Comment by wjbenfold** [comment]
The CLA seems mad at me @trexfeathers - I don't know if I've passed some limit on it or something?

**Comment by trexfeathers** [comment]
Hi @wjbenfold, hope you are well 😊

We switched to a new CLA service recently and last week it rechecked everything that was still open, which included several ideas of yours.

If we do get round to progressing your ideas 🤞, we may run into trouble since the author of your commits no longer exists, perhaps due to a switch in email addresses? Can either try to find an exemption, or with your blessing I suppose we could 're-author' your commits!

**Comment by wjbenfold** [comment]
Hi @trexfeathers, I hope you are too. You're absolutely welcome to reauthor any of my commits that can be helpful to Iris (or anything else) - also ping me if there's anything of mine I should breathe a little life back into

**Pull request closed without merging**
